@startuml
'https://plantuml.com/class-diagram

package Backups
{
    package Entities
    {
        class BackupJob
        {

        }
        
        class Backup
        {
        
        }
        
        class JobObject 
        {
        
        }
        
        class RestorePoint
        {
        
        }
        
        class Storage
        {
        
        }
    }
    
    package Algorithms
    {   
        interface IStorageCreationAlgorithm
        {
        }
        
        class SingleStorageAlgorithm 
        {
        }
        
        class SplitStoragesAlgorithm
        {
        }
    }
    
    package Repository
    {
        interface IRepository
        {
        }
        
        interface ICompressor
        {
        }
        
        class LocalFilesRepository
        {
        }
        
        class LocalMemoryRepository
        {
        }
        
        class ZipArchiveCompressor
        {
        }
    }

        
    BackupJob "1" o-- "0..n" JobObject: contains
    BackupJob "1" *-- "1" Backup: creates&contains
    BackupJob "1" ..> "1" RestorePoint: creates
    BackupJob "1" ..> "1" Storage: creates
    BackupJob "1" o-- "1" IRepository: contains&uses
    BackupJob "1" o-- "1" IStorageCreationAlgorithm: contains&uses
    Backup "1" *-- "0..n" RestorePoint: comprises
    RestorePoint "1" *-- "0..n" Storage: comprises
    
    IRepository "1" <.. "1" IStorageCreationAlgorithm: uses
    IRepository <|.. LocalFilesRepository: implements
    IRepository <|.. LocalMemoryRepository: implements
    ICompressor <|.. ZipArchiveCompressor: implements
    LocalFilesRepository "1" o-- "1" ICompressor: contains&uses
    
    IStorageCreationAlgorithm <|.. SingleStorageAlgorithm: implements
    IStorageCreationAlgorithm <|.. SplitStoragesAlgorithm: implements 
}

package BackupsClient
{
}

package BackupsServer
{
}

@enduml